const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../.env") });
const mongoose = require("mongoose");
const Roommate = require("../models/Roommate");

const sampleRoommates = [
  {
    name: "Brian Omondi",
    school: "Jomo Kenyatta University (JKUAT)",
    subtitle: "Studying Engineering",
    matchPercent: 95,
    tags: ["Studying Engineering", "Non-smoker", "Quiet during exams"],
    gender: "male",
    budget: 14000,
    nearCampus: true,
    quizCompletion: 80,
    cleanliness: "very tidy",
    sleepSchedule: "night owl",
    studyHabits: "quiet/focused",
    socialLevel: "somewhat social",
    highlights: [],
    quote:
      "Looking for a clean, focused housemate near the main gate. I spend most of my time in the lab but enjoy cooking on weekends.",
    photoUrl: "https://i.pravatar.cc/300?img=12",
    verified: true,
    featured: true,
    status: "approved",
  },
  {
    name: "Sarah Wangari",
    school: "University of Nairobi",
    subtitle: "Final year Medicine",
    matchPercent: 88,
    tags: ["Medicine", "Early riser"],
    gender: "female",
    budget: 18000,
    nearCampus: true,
    highlights: ["Loves morning runs", "Final year Medicine"],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=47",
    verified: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Kevin Mutua",
    school: "Kenyatta University",
    subtitle: "IT Student · Non-smoker",
    matchPercent: 82,
    tags: ["IT Student", "Non-smoker"],
    gender: "male",
    budget: 12000,
    nearCampus: false,
    highlights: [],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=33",
    verified: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Linet Adhiambo",
    school: "Strathmore University",
    subtitle: "Business Admin · Quiet",
    matchPercent: 79,
    tags: ["Business Admin", "Quiet"],
    gender: "female",
    budget: 16000,
    nearCampus: true,
    highlights: [],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=45",
    verified: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Davis Kimani",
    school: "USIU-Africa",
    subtitle: "Law Student · Early riser",
    matchPercent: 75,
    tags: ["Law Student", "Early riser"],
    gender: "male",
    budget: 15000,
    nearCampus: false,
    highlights: [],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=14",
    verified: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Faith Njeri",
    school: "JKUAT",
    subtitle: "Studying Engineering · Vegetarian",
    matchPercent: 91,
    tags: ["Studying Engineering", "Vegetarian", "Non-smoker"],
    gender: "female",
    budget: 13500,
    nearCampus: true,
    highlights: ["Vegetarian cook", "Studies late"],
    quote: "I keep a tidy space and enjoy quiet study sessions.",
    photoUrl: "https://i.pravatar.cc/300?img=48",
    verified: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Peter Otieno",
    school: "University of Nairobi",
    subtitle: "Business Student · Sociable",
    matchPercent: 70,
    tags: ["Business", "Sociable"],
    gender: "male",
    budget: 20000,
    nearCampus: false,
    highlights: [],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=15",
    verified: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Mercy Wambui",
    school: "Kenyatta University",
    subtitle: "Nursing Student · Non-smoker",
    matchPercent: 85,
    tags: ["Nursing", "Non-smoker", "Early riser"],
    gender: "female",
    budget: 11000,
    nearCampus: true,
    highlights: ["Early riser", "Loves cooking"],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=49",
    verified: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Samuel Kiprotich",
    school: "JKUAT",
    subtitle: "Studying Engineering · Athlete",
    matchPercent: 77,
    tags: ["Studying Engineering", "Athlete"],
    gender: "male",
    budget: 14500,
    nearCampus: true,
    highlights: [],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=51",
    verified: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Grace Achieng",
    school: "Strathmore University",
    subtitle: "Computer Science · Night owl",
    matchPercent: 80,
    tags: ["Computer Science", "Night owl"],
    gender: "female",
    budget: 17000,
    nearCampus: false,
    highlights: ["Gamer", "Studies at night"],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=44",
    verified: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Dennis Mwangi",
    school: "USIU-Africa",
    subtitle: "Journalism Student · Social",
    matchPercent: 68,
    tags: ["Journalism", "Social"],
    gender: "male",
    budget: 19000,
    nearCampus: false,
    highlights: [],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=52",
    verified: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Esther Chebet",
    school: "University of Nairobi",
    subtitle: "Studying Engineering · Quiet",
    matchPercent: 89,
    tags: ["Studying Engineering", "Quiet", "Non-smoker"],
    gender: "female",
    budget: 14000,
    nearCampus: true,
    highlights: ["Very tidy", "Quiet during exams"],
    quote: "Looking for someone respectful of shared space and study time.",
    photoUrl: "https://i.pravatar.cc/300?img=32",
    verified: true,
    featured: false,
    status: "approved",
  },
  {
    name: "Collins Odhiambo",
    school: "Kenyatta University",
    subtitle: "Architecture Student · Neat",
    matchPercent: 73,
    tags: ["Architecture", "Neat"],
    gender: "male",
    budget: 13000,
    nearCampus: true,
    highlights: [],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=53",
    verified: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Joyce Naliaka",
    school: "JKUAT",
    subtitle: "Studying Engineering · Female Only preference",
    matchPercent: 84,
    tags: ["Studying Engineering", "Female Only"],
    gender: "female",
    budget: 12500,
    nearCampus: false,
    highlights: ["Prefers female roommates", "Studious"],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=46",
    verified: false,
    featured: false,
    status: "approved",
  },
  {
    name: "Brian Kiptoo",
    school: "Strathmore University",
    subtitle: "Finance Student · Early riser",
    matchPercent: 66,
    tags: ["Finance", "Early riser"],
    gender: "male",
    budget: 21000,
    nearCampus: false,
    highlights: [],
    quote: "",
    photoUrl: "https://i.pravatar.cc/300?img=13",
    verified: false,
    featured: false,
    status: "approved",
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.CONNECTION_STRING);
    console.log("Database connection is ready");

    // Clear existing roommates so re-running this script doesn't create duplicates
    await Roommate.deleteMany({});
    console.log("Cleared existing roommates");

    const inserted = await Roommate.insertMany(sampleRoommates);
    console.log(`Seeded ${inserted.length} roommates`);

    process.exit(0);
  } catch (err) {
    console.error("Seeding failed:", err);
    process.exit(1);
  }
}

seed();